version: '3.8'

services:
  app:
    container_name: ${PROJECT_NAME}-server
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - qr_db
    env_file: .env
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    volumes:
      - .:/code
    restart: always

  qr_db:
    image: postgres:15-alpine
    container_name: qr_db_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: