version: '3.8'

services:
  server:
    container_name: ${PROJECT_NAME}-server
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "uvicorn app.src.main:app --reload --port=8084 --host=0.0.0.0"
    depends_on:
      - qr_db
    env_file: .env
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    volumes:
      - .:/code
    restart: always

  qr_db:
    image: postgres:15-alpine
    container_name: qr_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: